# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestdataalgo():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testdataalgo(self):
    # Test name: test-dataalgo
    # Step # | name | target | value
    # 1 | open | https://www.geeksforgeeks.org/ | 
    self.driver.get("https://www.geeksforgeeks.org/")
    # 2 | setWindowSize | 712x697 | 
    self.driver.set_window_size(712, 697)
    # 3 | click | linkText=Data Structures and Algorithms | 
    self.driver.find_element(By.LINK_TEXT, "Data Structures and Algorithms").click()
    # 4 | runScript | window.scrollTo(0,188) | 
    self.driver.execute_script("window.scrollTo(0,188)")
    # 5 | click | linkText=What is Data Structure? | 
    self.driver.find_element(By.LINK_TEXT, "What is Data Structure?").click()
    # 6 | runScript | window.scrollTo(0,2260.800048828125) | 
    self.driver.execute_script("window.scrollTo(0,2260.800048828125)")
    # 7 | runScript | window.scrollTo(0,2477.60009765625) | 
    self.driver.execute_script("window.scrollTo(0,2477.60009765625)")
    # 8 | runScript | window.scrollTo(0,2993.60009765625) | 
    self.driver.execute_script("window.scrollTo(0,2993.60009765625)")
    # 9 | runScript | window.scrollTo(0,3252.800048828125) | 
    self.driver.execute_script("window.scrollTo(0,3252.800048828125)")
    # 10 | click | linkText=2. Learn Data Structures | 
    self.driver.find_element(By.LINK_TEXT, "2. Learn Data Structures").click()
    # 11 | runScript | window.scrollTo(0,11420.7998046875) | 
    self.driver.execute_script("window.scrollTo(0,11420.7998046875)")
    # 12 | click | linkText=Binary tree | 
    self.driver.find_element(By.LINK_TEXT, "Binary tree").click()
    # 13 | mouseOver | linkText=Practice Problems on Binary Tree ! | 
    element = self.driver.find_element(By.LINK_TEXT, "Practice Problems on Binary Tree !")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 14 | runScript | window.scrollTo(0,227.1999969482422) | 
    self.driver.execute_script("window.scrollTo(0,227.1999969482422)")
    # 15 | runScript | window.scrollTo(0,407.20001220703125) | 
    self.driver.execute_script("window.scrollTo(0,407.20001220703125)")
    # 16 | runScript | window.scrollTo(0,837.5999755859375) | 
    self.driver.execute_script("window.scrollTo(0,837.5999755859375)")
    # 17 | runScript | window.scrollTo(0,1282.4000244140625) | 
    self.driver.execute_script("window.scrollTo(0,1282.4000244140625)")
  
